package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BaseItems;

/**
 * Generated by Jboot.
 */
@Table(tableName = "items", primaryKey = "id")
public class Items extends BaseItems<Items> {
	
}
