package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BaseUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user", primaryKey = "id")
public class User extends BaseUser<User> {
	
}
