package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BaseAccount;

/**
 * Generated by Jboot.
 */
@Table(tableName = "account", primaryKey = "id")
public class Account extends BaseAccount<Account> {
	
}
