package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BaseArticle;

/**
 * Generated by Jboot.
 */
@Table(tableName = "article", primaryKey = "id")
public class Article extends BaseArticle<Article> {
	
}
