package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BaseAuthor;

/**
 * Generated by Jboot.
 */
@Table(tableName = "author", primaryKey = "id")
public class Author extends BaseAuthor<Author> {
	
}
