package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BaseCategory;

/**
 * Generated by Jboot.
 */
@Table(tableName = "category", primaryKey = "id")
public class Category extends BaseCategory<Category> {
	
}
