package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayAddressUseRecord;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_address_use_record", primaryKey = "id")
public class PayAddressUseRecord extends BasePayAddressUseRecord<PayAddressUseRecord> {
	
}
