package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayAddressBlacklistRecord;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_address_blacklist_record", primaryKey = "id")
public class PayAddressBlacklistRecord extends BasePayAddressBlacklistRecord<PayAddressBlacklistRecord> {
	
}
