package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayAddressUse;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_address_use", primaryKey = "id")
public class PayAddressUse extends BasePayAddressUse<PayAddressUse> {
	
}
