package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayAddressBlacklist;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_address_blacklist", primaryKey = "id")
public class PayAddressBlacklist extends BasePayAddressBlacklist<PayAddressBlacklist> {
	
}
