package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayCoinManagePayment;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_coin_manage_payment", primaryKey = "id")
public class PayCoinManagePayment extends BasePayCoinManagePayment<PayCoinManagePayment> {
	
}
