package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayCoinInfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_coin_info", primaryKey = "id")
public class PayCoinInfo extends BasePayCoinInfo<PayCoinInfo> {
	
}
