package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayCoinManageOtc;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_coin_manage_otc", primaryKey = "id")
public class PayCoinManageOtc extends BasePayCoinManageOtc<PayCoinManageOtc> {
	
}
