package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayCommonConfig;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_common_config", primaryKey = "id")
public class PayCommonConfig extends BasePayCommonConfig<PayCommonConfig> {
	
}
