package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayCoinManageRed;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_coin_manage_red", primaryKey = "id")
public class PayCoinManageRed extends BasePayCoinManageRed<PayCoinManageRed> {
	
}
