package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayCoinConvertManage;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_coin_convert_manage", primaryKey = "id")
public class PayCoinConvertManage extends BasePayCoinConvertManage<PayCoinConvertManage> {
	
}
