package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayCoinManageGeneral;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_coin_manage_general", primaryKey = "id")
public class PayCoinManageGeneral extends BasePayCoinManageGeneral<PayCoinManageGeneral> {
	
}
