package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayCoinManageQuick;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_coin_manage_quick", primaryKey = "id")
public class PayCoinManageQuick extends BasePayCoinManageQuick<PayCoinManageQuick> {
	
}
