package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayDiscoverManage;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_discover_manage", primaryKey = "id")
public class PayDiscoverManage extends BasePayDiscoverManage<PayDiscoverManage> {
	
}
