package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayLanguage;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_language", primaryKey = "id")
public class PayLanguage extends BasePayLanguage<PayLanguage> {
	
}
