package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_role", primaryKey = "id")
public class PayRole extends BasePayRole<PayRole> {
	
}
