package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayRoleUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_role_user", primaryKey = "id")
public class PayRoleUser extends BasePayRoleUser<PayRoleUser> {
	
}
