package com.linging.model;

import io.jboot.db.annotation.Table;
import com.linging.model.base.BasePayRoleCoinManage;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pay_role_coin_manage", primaryKey = "id")
public class PayRoleCoinManage extends BasePayRoleCoinManage<PayRoleCoinManage> {
	
}
