package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayRole<M extends BasePayRole<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 角色名
	 */
	public void setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
	}

    /**
     * 角色名
     */
	public java.lang.String getRoleName() {
		return getStr("role_name");
	}

	/**
	 * 备注
	 */
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

    /**
     * 备注
     */
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	/**
	 * 权限组(多个,分割)
【
1:Pay提币手续费减免，
2:Pay转账手续费减免，
3:Pay彩蛋手续费减免，
4.Pay提币不限额，
5.Pay转账不限额，
6.Pay彩蛋不限额，
】
	 */
	public void setGroupCode(java.lang.String groupCode) {
		set("group_code", groupCode);
	}

    /**
     * 权限组(多个,分割)
【
1:Pay提币手续费减免，
2:Pay转账手续费减免，
3:Pay彩蛋手续费减免，
4.Pay提币不限额，
5.Pay转账不限额，
6.Pay彩蛋不限额，
】
     */
	public java.lang.String getGroupCode() {
		return getStr("group_code");
	}

	/**
	 * 删除标记[0:未删除，1：已删除]
	 */
	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}

    /**
     * 删除标记[0:未删除，1：已删除]
     */
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

    /**
     * 创建人
     */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}

	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

    /**
     * 修改人
     */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

    /**
     * 修改时间
     */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}

}
