package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayAddressUseRecord<M extends BasePayAddressUseRecord<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

    /**
     * 用户id
     */
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	/**
	 * 主链名称
	 */
	public void setCoinCode(java.lang.String coinCode) {
		set("coin_code", coinCode);
	}

    /**
     * 主链名称
     */
	public java.lang.String getCoinCode() {
		return getStr("coin_code");
	}

	/**
	 * 更换前的地址
	 */
	public void setBeforeAddress(java.lang.String beforeAddress) {
		set("before_address", beforeAddress);
	}

    /**
     * 更换前的地址
     */
	public java.lang.String getBeforeAddress() {
		return getStr("before_address");
	}

	/**
	 * 更换后的地址
	 */
	public void setAfterAddress(java.lang.String afterAddress) {
		set("after_address", afterAddress);
	}

    /**
     * 更换后的地址
     */
	public java.lang.String getAfterAddress() {
		return getStr("after_address");
	}

	/**
	 * 备注
	 */
	public void setRemarks(java.lang.String remarks) {
		set("remarks", remarks);
	}

    /**
     * 备注
     */
	public java.lang.String getRemarks() {
		return getStr("remarks");
	}

	/**
	 * 删除标记[0:未删除，1：已删除]
	 */
	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}

    /**
     * 删除标记[0:未删除，1：已删除]
     */
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

    /**
     * 创建人
     */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}

	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

    /**
     * 修改人
     */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

    /**
     * 修改时间
     */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}

}
