package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayCoinConvertManage<M extends BasePayCoinConvertManage<M>> extends JbootModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}

    /**
     * ID
     */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 交易对唯一
	 */
	public void setConvertCoinName(java.lang.String convertCoinName) {
		set("convert_coin_name", convertCoinName);
	}

    /**
     * 交易对唯一
     */
	public java.lang.String getConvertCoinName() {
		return getStr("convert_coin_name");
	}

	/**
	 * 手续费百分比(如：10%,填10)
	 */
	public void setConvertFee(java.math.BigDecimal convertFee) {
		set("convert_fee", convertFee);
	}

    /**
     * 手续费百分比(如：10%,填10)
     */
	public java.math.BigDecimal getConvertFee() {
		return get("convert_fee");
	}

	/**
	 * 买方抛单比例（百分比）
	 */
	public void setBuyProportion(java.math.BigDecimal buyProportion) {
		set("buy_proportion", buyProportion);
	}

    /**
     * 买方抛单比例（百分比）
     */
	public java.math.BigDecimal getBuyProportion() {
		return get("buy_proportion");
	}

	/**
	 * 卖方抛单比例（百分比）
	 */
	public void setSellProportion(java.math.BigDecimal sellProportion) {
		set("sell_proportion", sellProportion);
	}

    /**
     * 卖方抛单比例（百分比）
     */
	public java.math.BigDecimal getSellProportion() {
		return get("sell_proportion");
	}

	/**
	 * 买方单笔最大
	 */
	public void setBuyMaxSingleLimit(java.math.BigDecimal buyMaxSingleLimit) {
		set("buy_max_single_limit", buyMaxSingleLimit);
	}

    /**
     * 买方单笔最大
     */
	public java.math.BigDecimal getBuyMaxSingleLimit() {
		return get("buy_max_single_limit");
	}

	/**
	 * 卖方单笔最大
	 */
	public void setSellMaxSingleLimit(java.math.BigDecimal sellMaxSingleLimit) {
		set("sell_max_single_limit", sellMaxSingleLimit);
	}

    /**
     * 卖方单笔最大
     */
	public java.math.BigDecimal getSellMaxSingleLimit() {
		return get("sell_max_single_limit");
	}

	/**
	 * 买方日限额
	 */
	public void setBuyDayLimit(java.math.BigDecimal buyDayLimit) {
		set("buy_day_limit", buyDayLimit);
	}

    /**
     * 买方日限额
     */
	public java.math.BigDecimal getBuyDayLimit() {
		return get("buy_day_limit");
	}

	/**
	 * 卖方日限额
	 */
	public void setSellDayLimit(java.math.BigDecimal sellDayLimit) {
		set("sell_day_limit", sellDayLimit);
	}

    /**
     * 卖方日限额
     */
	public java.math.BigDecimal getSellDayLimit() {
		return get("sell_day_limit");
	}

	/**
	 * 买方单笔最小
	 */
	public void setBuyMinSingleLimit(java.math.BigDecimal buyMinSingleLimit) {
		set("buy_min_single_limit", buyMinSingleLimit);
	}

    /**
     * 买方单笔最小
     */
	public java.math.BigDecimal getBuyMinSingleLimit() {
		return get("buy_min_single_limit");
	}

	/**
	 * 卖方单笔最小
	 */
	public void setSellMinSingleLimit(java.math.BigDecimal sellMinSingleLimit) {
		set("sell_min_single_limit", sellMinSingleLimit);
	}

    /**
     * 卖方单笔最小
     */
	public java.math.BigDecimal getSellMinSingleLimit() {
		return get("sell_min_single_limit");
	}

	/**
	 * 数量精度
	 */
	public void setAmountAccuracy(java.lang.Integer amountAccuracy) {
		set("amount_accuracy", amountAccuracy);
	}

    /**
     * 数量精度
     */
	public java.lang.Integer getAmountAccuracy() {
		return getInt("amount_accuracy");
	}

	/**
	 * 价格精度
	 */
	public void setPriceAccuracy(java.lang.Integer priceAccuracy) {
		set("price_accuracy", priceAccuracy);
	}

    /**
     * 价格精度
     */
	public java.lang.Integer getPriceAccuracy() {
		return getInt("price_accuracy");
	}

	/**
	 * 删除标记[0:未删除，1：已删除]
	 */
	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}

    /**
     * 删除标记[0:未删除，1：已删除]
     */
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

    /**
     * 创建人
     */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 创建日期
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

    /**
     * 创建日期
     */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}

	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

    /**
     * 修改人
     */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	/**
	 * 修改日期
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

    /**
     * 修改日期
     */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}

}
