package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayAddressBlacklist<M extends BasePayAddressBlacklist<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 币种
	 */
	public void setCoin(java.lang.String coin) {
		set("coin", coin);
	}

    /**
     * 币种
     */
	public java.lang.String getCoin() {
		return getStr("coin");
	}

	/**
	 * 地址
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}

    /**
     * 地址
     */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * 状态（0:启动; 1禁用)
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

    /**
     * 状态（0:启动; 1禁用)
     */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 删除标记[0:未删除，1：已删除]'
	 */
	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}

    /**
     * 删除标记[0:未删除，1：已删除]'
     */
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

    /**
     * 创建人
     */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}

	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

    /**
     * 修改人
     */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

    /**
     * 修改时间
     */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}

}
