package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayDiscoverManage<M extends BasePayDiscoverManage<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}

    /**
     * 主键
     */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 类型(1.Mighty Pay，2.HD钱包，3.闪兑，4.积分商城，5.游戏，6.DAPP，7.金融)
	 */
	public void setDiscoverType(java.lang.Integer discoverType) {
		set("discover_type", discoverType);
	}

    /**
     * 类型(1.Mighty Pay，2.HD钱包，3.闪兑，4.积分商城，5.游戏，6.DAPP，7.金融)
     */
	public java.lang.Integer getDiscoverType() {
		return getInt("discover_type");
	}

	/**
	 * 背景图片
	 */
	public void setDiscoverBackimg(java.lang.String discoverBackimg) {
		set("discover_backImg", discoverBackimg);
	}

    /**
     * 背景图片
     */
	public java.lang.String getDiscoverBackimg() {
		return getStr("discover_backImg");
	}

	/**
	 * 右侧图标
	 */
	public void setDiscoverHeader(java.lang.String discoverHeader) {
		set("discover_header", discoverHeader);
	}

    /**
     * 右侧图标
     */
	public java.lang.String getDiscoverHeader() {
		return getStr("discover_header");
	}

	/**
	 * h5链接
	 */
	public void setDiscoverLinkUrl(java.lang.String discoverLinkUrl) {
		set("discover_link_url", discoverLinkUrl);
	}

    /**
     * h5链接
     */
	public java.lang.String getDiscoverLinkUrl() {
		return getStr("discover_link_url");
	}

	/**
	 * 0: 竖屏, 1: 横屏
	 */
	public void setOrientation(java.lang.Integer orientation) {
		set("orientation", orientation);
	}

    /**
     * 0: 竖屏, 1: 横屏
     */
	public java.lang.Integer getOrientation() {
		return getInt("orientation");
	}

	/**
	 * 是否隐藏标题  0: 不隐藏 1:隐藏
	 */
	public void setHideTitle(java.lang.Integer hideTitle) {
		set("hide_title", hideTitle);
	}

    /**
     * 是否隐藏标题  0: 不隐藏 1:隐藏
     */
	public java.lang.Integer getHideTitle() {
		return getInt("hide_title");
	}

	/**
	 * 是否可用(1：是， 0:否 )
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

    /**
     * 是否可用(1：是， 0:否 )
     */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 删除标记[0:未删除，1：已删除]
	 */
	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}

    /**
     * 删除标记[0:未删除，1：已删除]
     */
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

    /**
     * 创建人
     */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}

	/**
	 * 更新人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

    /**
     * 更新人
     */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

    /**
     * 更新时间
     */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}

}
