package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayRoleUser<M extends BasePayRoleUser<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}

    /**
     * 主键id
     */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 角色id
	 */
	public void setRoleId(java.lang.String roleId) {
		set("role_id", roleId);
	}

    /**
     * 角色id
     */
	public java.lang.String getRoleId() {
		return getStr("role_id");
	}

	/**
	 * 用户id
	 */
	public void setUserId(java.lang.String userId) {
		set("user_id", userId);
	}

    /**
     * 用户id
     */
	public java.lang.String getUserId() {
		return getStr("user_id");
	}

	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

    /**
     * 创建人
     */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}

}
