package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayCoinManageQuick<M extends BasePayCoinManageQuick<M>> extends JbootModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}

    /**
     * ID
     */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 币种简称
	 */
	public void setCoin(java.lang.String coin) {
		set("coin", coin);
	}

    /**
     * 币种简称
     */
	public java.lang.String getCoin() {
		return getStr("coin");
	}

	/**
	 * 快速最小收款数量
	 */
	public void setMinReceipt(java.math.BigDecimal minReceipt) {
		set("min_receipt", minReceipt);
	}

    /**
     * 快速最小收款数量
     */
	public java.math.BigDecimal getMinReceipt() {
		return get("min_receipt");
	}

	/**
	 * 快速转账手续费率类型：0固定数字货币；1百分比
	 */
	public void setTransType(java.lang.Integer transType) {
		set("trans_type", transType);
	}

    /**
     * 快速转账手续费率类型：0固定数字货币；1百分比
     */
	public java.lang.Integer getTransType() {
		return getInt("trans_type");
	}

	/**
	 * 快速转账手续费
	 */
	public void setFeeRatioTrans(java.math.BigDecimal feeRatioTrans) {
		set("fee_ratio_trans", feeRatioTrans);
	}

    /**
     * 快速转账手续费
     */
	public java.math.BigDecimal getFeeRatioTrans() {
		return get("fee_ratio_trans");
	}

	/**
	 * 限额类型：0:根据数字货币限额；1:根据法币限额(USD)
	 */
	public void setLimitType(java.lang.Integer limitType) {
		set("limit_type", limitType);
	}

    /**
     * 限额类型：0:根据数字货币限额；1:根据法币限额(USD)
     */
	public java.lang.Integer getLimitType() {
		return getInt("limit_type");
	}

	/**
	 * 单笔转账限额
	 */
	public void setSingleLimitTransfer(java.math.BigDecimal singleLimitTransfer) {
		set("single_limit_transfer", singleLimitTransfer);
	}

    /**
     * 单笔转账限额
     */
	public java.math.BigDecimal getSingleLimitTransfer() {
		return get("single_limit_transfer");
	}

	/**
	 * 单日转账限额
	 */
	public void setDayLimitTransfer(java.math.BigDecimal dayLimitTransfer) {
		set("day_limit_transfer", dayLimitTransfer);
	}

    /**
     * 单日转账限额
     */
	public java.math.BigDecimal getDayLimitTransfer() {
		return get("day_limit_transfer");
	}

	/**
	 * 手续费最大限制
	 */
	public void setMaxFee(java.math.BigDecimal maxFee) {
		set("max_fee", maxFee);
	}

    /**
     * 手续费最大限制
     */
	public java.math.BigDecimal getMaxFee() {
		return get("max_fee");
	}

	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

    /**
     * 创建人
     */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 创建日期
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

    /**
     * 创建日期
     */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}

	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

    /**
     * 修改人
     */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	/**
	 * 修改日期
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

    /**
     * 修改日期
     */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}

	/**
	 * 删除标记[0:未删除，1：已删除]
	 */
	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}

    /**
     * 删除标记[0:未删除，1：已删除]
     */
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

}
