package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayCoinManageOtc<M extends BasePayCoinManageOtc<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}

    /**
     * 主键
     */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 币种名称
	 */
	public void setCoin(java.lang.String coin) {
		set("coin", coin);
	}

    /**
     * 币种名称
     */
	public java.lang.String getCoin() {
		return getStr("coin");
	}

	/**
	 * 买方手续费百分比(如：10%,填10)
	 */
	public void setBuyerFee(java.math.BigDecimal buyerFee) {
		set("buyer_fee", buyerFee);
	}

    /**
     * 买方手续费百分比(如：10%,填10)
     */
	public java.math.BigDecimal getBuyerFee() {
		return get("buyer_fee");
	}

	/**
	 * 卖方手续费百分比（如：10%，填10）
	 */
	public void setSellerFee(java.math.BigDecimal sellerFee) {
		set("seller_fee", sellerFee);
	}

    /**
     * 卖方手续费百分比（如：10%，填10）
     */
	public java.math.BigDecimal getSellerFee() {
		return get("seller_fee");
	}

	/**
	 * 数量精度
	 */
	public void setAmountAccuracy(java.lang.Integer amountAccuracy) {
		set("amount_accuracy", amountAccuracy);
	}

    /**
     * 数量精度
     */
	public java.lang.Integer getAmountAccuracy() {
		return getInt("amount_accuracy");
	}

	/**
	 * 价格精度
	 */
	public void setPriceAccuracy(java.lang.Integer priceAccuracy) {
		set("price_accuracy", priceAccuracy);
	}

    /**
     * 价格精度
     */
	public java.lang.Integer getPriceAccuracy() {
		return getInt("price_accuracy");
	}

	/**
	 * 删除标记（0:未删除，1：已删除）
	 */
	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}

    /**
     * 删除标记（0:未删除，1：已删除）
     */
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

    /**
     * 创建人
     */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}

	/**
	 * 更新人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

    /**
     * 更新人
     */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

    /**
     * 更新时间
     */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}

}
