package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayCoinManagePayment<M extends BasePayCoinManagePayment<M>> extends JbootModel<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}

    /**
     * ID
     */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 币种简称
	 */
	public void setCoin(java.lang.String coin) {
		set("coin", coin);
	}

    /**
     * 币种简称
     */
	public java.lang.String getCoin() {
		return getStr("coin");
	}

	/**
	 * 最低付款数量
	 */
	public void setMinPayment(java.math.BigDecimal minPayment) {
		set("min_payment", minPayment);
	}

    /**
     * 最低付款数量
     */
	public java.math.BigDecimal getMinPayment() {
		return get("min_payment");
	}

	/**
	 * 单日付款限额
	 */
	public void setDayLimitPayment(java.math.BigDecimal dayLimitPayment) {
		set("day_limit_payment", dayLimitPayment);
	}

    /**
     * 单日付款限额
     */
	public java.math.BigDecimal getDayLimitPayment() {
		return get("day_limit_payment");
	}

	/**
	 * 限额类型：0:根据数字货币限额；1:根据法币限额(USD)
	 */
	public void setLimitType(java.lang.Integer limitType) {
		set("limit_type", limitType);
	}

    /**
     * 限额类型：0:根据数字货币限额；1:根据法币限额(USD)
     */
	public java.lang.Integer getLimitType() {
		return getInt("limit_type");
	}

	/**
	 * 单笔付款限额
	 */
	public void setSingleLimitPayment(java.math.BigDecimal singleLimitPayment) {
		set("single_limit_payment", singleLimitPayment);
	}

    /**
     * 单笔付款限额
     */
	public java.math.BigDecimal getSingleLimitPayment() {
		return get("single_limit_payment");
	}

	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

    /**
     * 创建人
     */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 创建日期
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

    /**
     * 创建日期
     */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}

	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

    /**
     * 修改人
     */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	/**
	 * 修改日期
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

    /**
     * 修改日期
     */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}

	/**
	 * 删除标记[0:未删除，1：已删除]
	 */
	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}

    /**
     * 删除标记[0:未删除，1：已删除]
     */
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

}
