package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayCommonConfig<M extends BasePayCommonConfig<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 类目
	 */
	public void setLable(java.lang.String lable) {
		set("lable", lable);
	}

    /**
     * 类目
     */
	public java.lang.String getLable() {
		return getStr("lable");
	}

	/**
	 * 配置名称
	 */
	public void setConfigKey(java.lang.String configKey) {
		set("config_key", configKey);
	}

    /**
     * 配置名称
     */
	public java.lang.String getConfigKey() {
		return getStr("config_key");
	}

	/**
	 * 配置值
	 */
	public void setConfigValue(java.lang.String configValue) {
		set("config_value", configValue);
	}

    /**
     * 配置值
     */
	public java.lang.String getConfigValue() {
		return getStr("config_value");
	}

	/**
	 * 属性1
	 */
	public void setAttr1(java.lang.String attr1) {
		set("attr1", attr1);
	}

    /**
     * 属性1
     */
	public java.lang.String getAttr1() {
		return getStr("attr1");
	}

	/**
	 * 属性2
	 */
	public void setAttr2(java.lang.String attr2) {
		set("attr2", attr2);
	}

    /**
     * 属性2
     */
	public java.lang.String getAttr2() {
		return getStr("attr2");
	}

	/**
	 * 属性3
	 */
	public void setAttr3(java.lang.String attr3) {
		set("attr3", attr3);
	}

    /**
     * 属性3
     */
	public java.lang.String getAttr3() {
		return getStr("attr3");
	}

	/**
	 * 属性4
	 */
	public void setAttr4(java.lang.String attr4) {
		set("attr4", attr4);
	}

    /**
     * 属性4
     */
	public java.lang.String getAttr4() {
		return getStr("attr4");
	}

	/**
	 * 描述
	 */
	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

    /**
     * 描述
     */
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	/**
	 * 操作类别
	 */
	public void setOpType(java.lang.String opType) {
		set("op_type", opType);
	}

    /**
     * 操作类别
     */
	public java.lang.String getOpType() {
		return getStr("op_type");
	}

	/**
	 * 状态
	 */
	public void setConfigStatus(java.lang.Integer configStatus) {
		set("config_status", configStatus);
	}

    /**
     * 状态
     */
	public java.lang.Integer getConfigStatus() {
		return getInt("config_status");
	}

	/**
	 * 删除标记[0:未删除，1：已删除]
	 */
	public void setDelFlag(java.lang.Integer delFlag) {
		set("del_flag", delFlag);
	}

    /**
     * 删除标记[0:未删除，1：已删除]
     */
	public java.lang.Integer getDelFlag() {
		return getInt("del_flag");
	}

	/**
	 * 创建人
	 */
	public void setCreateBy(java.lang.String createBy) {
		set("create_by", createBy);
	}

    /**
     * 创建人
     */
	public java.lang.String getCreateBy() {
		return getStr("create_by");
	}

	/**
	 * 创建时间
	 */
	public void setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreateDate() {
		return getDate("create_date");
	}

	/**
	 * 修改人
	 */
	public void setUpdateBy(java.lang.String updateBy) {
		set("update_by", updateBy);
	}

    /**
     * 修改人
     */
	public java.lang.String getUpdateBy() {
		return getStr("update_by");
	}

	/**
	 * 修改时间
	 */
	public void setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
	}

    /**
     * 修改时间
     */
	public java.util.Date getUpdateDate() {
		return getDate("update_date");
	}

}
