package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCategory<M extends BaseCategory<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

    /**
     * 主键
     */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 分类标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 分类标题
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 分类描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}

    /**
     * 分类描述
     */
	public java.lang.String getDescription() {
		return getStr("description");
	}

}
