package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

    /**
     * 主键
     */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 文章作者ID
	 */
	public void setAuthorId(java.lang.Long authorId) {
		set("author_id", authorId);
	}

    /**
     * 文章作者ID
     */
	public java.lang.Long getAuthorId() {
		return getLong("author_id");
	}

	/**
	 * 文章标题
	 */
	public void setTitle(java.lang.String title) {
		set("title", title);
	}

    /**
     * 文章标题
     */
	public java.lang.String getTitle() {
		return getStr("title");
	}

	/**
	 * 文章内容
	 */
	public void setContent(java.lang.String content) {
		set("content", content);
	}

    /**
     * 文章内容
     */
	public java.lang.String getContent() {
		return getStr("content");
	}

}
