package com.linging.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuthor<M extends BaseAuthor<M>> extends JbootModel<M> implements IBean {

	/**
	 * 主键
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

    /**
     * 主键
     */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 作者昵称
	 */
	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

    /**
     * 作者昵称
     */
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	/**
	 * 作者邮件
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}

    /**
     * 作者邮件
     */
	public java.lang.String getEmail() {
		return getStr("email");
	}

}
